package com.scm.eis.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum District {
    ARARIA("Araria"),
    ARWAL("Arwal"),
    AURANGABAD("Aurangabad"),
    BANKA("Banka"),
    BEGUSARAI("Begusarai"),
    BHAGALPUR("Bhagalpur"),
    BHOJPUR("Bhojpur"),
    BUXAR("Buxar"),
    DARBHANGA("Darbhanga"),
    EAST_CHAMPARAN("East Champaran"),
    GAYA("Gaya"),
    GOPALGANJ("Gopalganj"),
    JAMUI("Jamui"),
    JEHANABAD("Jehanabad"),
    KAIMUR("Kaimur"),
    KATIHAR("Katihar"),
    KHAGARIA("Khagaria"),
    KISHANGANJ("Kishanganj"),
    LAKHISARAI("Lakhisarai"),
    MADHEPURA("Madhepura"),
    MADHUBANI("Madhubani"),
    MUNGER("Munger"),
    MUZAFFARPUR("Muzaffarpur"),
    NALANDA("Nalanda"),
    NAWADA("Nawada"),
    PATNA("Patna"),
    PURNIA("Purnia"),
    ROHTAS("Rohtas"),
    SAHARSA("Saharsa"),
    SAMASTIPUR("Samastipur"),
    SARAN("Saran"),
    SHEIKHPURA("Sheikhpura"),
    SHEOHAR("Sheohar"),
    SITAMARHI("Sitamarhi"),
    SIWAN("Siwan"),
    SUPAUL("Supaul"),
    VAISHALI("Vaishali"),
    WEST_CHAMPARAN("West Champaran"),
    ANANTAPUR("Anantapur"),
    CHITTOOR("Chittoor"),
    EAST_GODAVARI("East Godavari"),
    GUNTUR("Guntur"),
    KADAPA("Kadapa"),
    KRISHNA("Krishna"),
    KURNOOL("Kurnool"),
    NELLORE("Nellore"),
    PRAKASAM("Prakasam"),
    SRIKAKULAM("Srikakulam"),
    VISAKHAPATNAM("Visakhapatnam"),
    VIZIANAGARAM("Vizianagaram"),
    WEST_GODAVARI("West Godavari"),
    ANJAW("Anjaw"),
    CHANGLANG("Changlang"),
    EAST_KAMENG("East Kameng"),
    EAST_SIANG("East Siang"),
    KRA_DADI("Kra Dadi"),
    KURUNG_KUMEY("Kurung Kumey"),
    LOHIT("Lohit"),
    LONGDING("Longding"),
    LOWER_DIBANG_VALLEY("Lower Dibang Valley"),
    LOWER_SUBANSIRI("Lower Subansiri"),
    NAMSAI("Namsai"),
    PAPUM_PARE("Papum Pare"),
    TAWANG("Tawang"),
    UPPER_DIBANG_VALLEY("Upper Dibang Valley"),
    UPPER_SIANG("Upper Siang"),
    UPPER_SUBANSIRI("Upper Subansiri"),
    WEST_KAMENG("West Kameng"),
    WEST_SIANG("West Siang"),
    BAKSA("Baksa"),
    BARPETA("Barpeta"),
    BISWANATH("Biswanath"),
    BONGAIGAON("Bongaigaon"),
    CACHAR("Cachar"),
    CHARAIDEO("Charaideo"),
    DARRANG("Darrang"),
    DHEMAJI("Dhemaji"),
    DHUBRI("Dhubri"),
    DIBRUGARH("Dibrugarh"),
    GOALPARA("Goalpara"),
    GOLAGHAT("Golaghat"),
    HOJAI("Hojai"),
    JORHAT("Jorhat"),
    KAMRUP("Kamrup"),
    KAMRUP_METRO("Kamrup Metropolitan"),
    KARBI_ANGLONG("Karbi Anglong"),
    KARIMGANJ("Karimganj"),
    KOKRAJHAR("Kokrajhar"),
    LAKHIMPUR("Lakhimpur"),
    MAJULI("Majuli"),
    MORIGAON("Morigaon"),
    NAGAON("Nagaon"),
    NALBARI("Nalbari"),
    SIVASAGAR("Sivasagar"),
    SONITPUR("Sonitpur"),
    SOUTH_SALMARA("South Salmara"),
    TINSUKIA("Tinsukia"),
    UDALGURI("Udalguri"),
    WEST_KARBI_ANGLONG("West Karbi Anglong"),
    BALOD("Balod"),
    BALODA_BAZAR("Baloda Bazar"),
    BALRAMPUR("Balrampur"),
    BASTAR("Bastar"),
    BEMETARA("Bemetara"),
    BIJAPUR("Bijapur"),
    BILASPUR("Bilaspur"),
    DANTEWADA("Dantewada"),
    DHAMTARI("Dhamtari"),
    DURG("Durg"),
    GARIABAND("Gariaband"),
    JANJGIR_CHAMPA("Janjgir-Champa"),
    JASHPUR("Jashpur"),
    KANKER("Kanker"),
    KAWARDHA("Kawardha"),
    KONDAGAON("Kondagaon"),
    KORBA("Korba"),
    KORIYA("Koriya"),
    MAHASAMUND("Mahasamund"),
    MUNGELI("Mungeli"),
    NARAYANPUR("Narayanpur"),
    RAIGARH("Raigarh"),
    RAIPUR("Raipur"),
    RAJNANDGAON("Rajnandgaon"),
    SUKMA("Sukma"),
    SURAJPUR("Surajpur"),
    SARGUJA("Sarguja"),
    CENTRAL_DELHI("Central Delhi"),
    EAST_DELHI("East Delhi"),
    NEW_DELHI("New Delhi"),
    NORTH_DELHI("North Delhi"),
    NORTH_EAST_DELHI("North East Delhi"),
    NORTH_WEST_DELHI("North West Delhi"),
    SHAHDARA("Shahdara"),
    SOUTH_DELHI("South Delhi"),
    SOUTH_EAST_DELHI("South East Delhi"),
    SOUTH_WEST_DELHI("South West Delhi"),
    WEST_DELHI("West Delhi"),
    AHMEDABAD("Ahmedabad"),
    AMRELI("Amreli"),
    ANAND("Anand"),
    ARAVALLI("Aravalli"),
    BANASKANTHA("Banaskantha"),
    BHARUCH("Bharuch"),
    BHAVNAGAR("Bhavnagar"),
    BOTAD("Botad"),
    CHHOTA_UDEPUR("Chhota Udepur"),
    DANG("Dang"),
    DEVBHOOMI_DWARKA("Devbhoomi Dwarka"),
    DANGS("Dangs"),
    GIR_SOMNATH("Gir Somnath"),
    JAMNAGAR("Jamnagar"),
    JUNAGADH("Junagadh"),
    KHEDA("Kheda"),
    KUTCH("Kutch"),
    MAHISAGAR("Mahisagar"),
    MEHSANA("Mehsana"),
    MORBI("Morbi"),
    NARMADA("Narmada"),
    NAVSARI("Navsari"),
    PANCHMAHALS("Panchmahal"),
    PATAN("Patan"),
    PORBANDAR("Porbandar"),
    RAJKOT("Rajkot"),
    SABARKANTHA("Sabarkantha"),
    SURAT("Surat"),
    SURENDRANAGAR("Surendranagar"),
    TAPI("Tapi"),
    VADODARA("Vadodara"),
    VALSAD("Valsad"),
    NORTH_GOA("North Goa"),
    SOUTH_GOA("South Goa"),
    AMBALA("Ambala"),
    BHIWANI("Bhiwani"),
    CHARKHI_DADRI("Charkhi Dadri"),
    FARIDABAD("Faridabad"),
    FATEHABAD("Fatehabad"),
    GURUGRAM("Gurugram"),
    HISAR("Hisar"),
    JHAJJAR("Jhajjar"),
    JIND("Jind"),
    KAITHAL("Kaithal"),
    KARNAL("Karnal"),
    KURUKSHETRA("Kurukshetra"),
    MAHENDRAGARH("Mahendragarh"),
    MEWAT("Mewat"),
    PALWAL("Palwal"),
    PANCHKULA("Panchkula"),
    PANIPAT("Panipat"),
    REWARI("Rewari"),
    ROHTAK("Rohtak"),
    SIRSA("Sirsa"),
    SONIPAT("Sonipat"),
    YAMUNANAGAR("Yamunanagar"),
    BILASPUR_HP("Bilaspur"),
    CHAMBA("Chamba"),
    HAMIRPUR_HP("Hamirpur"),
    KANGRA("Kangra"),
    KINNAUR("Kinnaur"),
    KULLU("Kullu"),
    LAHUL_SPITI("Lahul and Spiti"),
    MANDI("Mandi"),
    SHIMLA("Shimla"),
    SIRMAUR("Sirmaur"),
    SOLAN("Solan"),
    UNA("Una"),
    ANANTNAG("Anantnag"),
    BANDIPORA("Bandipora"),
    BARAMULLA("Baramulla"),
    BUDGAM("Budgam"),
    DODA("Doda"),
    GANDERBAL("Ganderbal"),
    JAMMU("Jammu"),
    KATHUA("Kathua"),
    KISHTWAR("Kishtwar"),
    KULGAM("Kulgam"),
    KUPWARA("Kupwara"),
    POONCH("Poonch"),
    PULWAMA("Pulwama"),
    RAJOURI("Rajouri"),
    RAMBAN("Ramban"),
    REASI("Reasi"),
    SAMBA("Samba"),
    SHOPIAN("Shopian"),
    SRINAGAR("Srinagar"),
    UDHAMPUR("Udhampur"),
    BOKARO("Bokaro"),
    CHATRA("Chatra"),
    DEOGHAR("Deoghar"),
    DHANBAD("Dhanbad"),
    DUMKA("Dumka"),
    EAST_SINGHBHUM("East Singhbhum"),
    GARHWA("Garhwa"),
    GIRIDIH("Giridih"),
    GODDA("Godda"),
    GUMLA("Gumla"),
    HAZARIBAGH("Hazaribagh"),
    JAMTARA("Jamtara"),
    KHUNTI("Khunti"),
    KODERMA("Koderma"),
    LATEHAR("Latehar"),
    LOHARDAGA("Lohardaga"),
    PAKUR("Pakur"),
    PALAMU("Palamu"),
    RAMGARH("Ramgarh"),
    RANCHI("Ranchi"),
    SAHIBGANJ("Sahibganj"),
    SIMDEGA("Simdega"),
    WEST_SINGHBHUM("West Singhbhum"),
    BAGALKOT("Bagalkot"),
    BALLARI("Ballari"),
    BELAGAVI("Belagavi"),
    BENGALURU_RURAL("Bengaluru Rural"),
    BENGALURU_URBAN("Bengaluru Urban"),
    BIDAR("Bidar"),
    CHAMARAJANAGAR("Chamarajanagar"),
    CHIKKABALLAPUR("Chikkaballapur"),
    CHIKKAMAGALURU("Chikkamagaluru"),
    CHITRADURGA("Chitradurga"),
    DAKSHINA_KANNADA("Dakshina Kannada"),
    DAVANAGERE("Davanagere"),
    DHARWAD("Dharwad"),
    GADAG("Gadag"),
    HASSAN("Hassan"),
    HAVERI("Haveri"),
    KALABURAGI("Kalaburagi"),
    KODAGU("Kodagu"),
    KOLAR("Kolar"),
    KOPPAL("Koppal"),
    MANDYA("Mandya"),
    MYSURU("Mysuru"),
    RAICHUR("Raichur"),
    RAMANAGARA("Ramanagara"),
    SHIVAMOGGA("Shivamogga"),
    TUMAKURU("Tumakuru"),
    UDUPI("Udupi"),
    UTTARA_KANNADA("Uttara Kannada"),
    VIJAYAPURA("Vijayapura"),
    YADGIR("Yadgir"),
    EAST_GARO_HILLS("East Garo Hills"),
    EAST_JAINTIA_HILLS("East Jaintia Hills"),
    EAST_KHASI_HILLS("East Khasi Hills"),
    NORTH_GARO_HILLS("North Garo Hills"),
    RI_BHOI("Ri Bhoi"),
    SOUTH_GARO_HILLS("South Garo Hills"),
    SOUTH_WEST_GARO_HILLS("South West Garo Hills"),
    SOUTH_WEST_KHASI_HILLS("South West Khasi Hills"),
    WEST_GARO_HILLS("West Garo Hills"),
    WEST_JAINTIA_HILLS("West Jaintia Hills"),
    WEST_KHASI_HILLS("West Khasi Hills"),
    AIZAWL("Aizawl"),
    CHAMPHAI("Champhai"),
    HNAHTHIAL("Hnahthial"),
    KHUAIBUNG("Khuaibung"),
    KOLASIB("Kolasib"),
    LAWNGTLAI("Lawngtlai"),
    LUNGLEI("Lunglei"),
    MAMIT("Mamit"),
    SAITUAL("Saitual"),
    SERCHHIP("Serchhip"),
    CHUMUKEDIMA("Chumukedima"),
    DIMAPUR("Dimapur"),
    KIPHIRE("Kiphire"),
    KOHIMA("Kohima"),
    LONGLENG("Longleng"),
    MOKOKCHUNG("Mokokchung"),
    MON("Mon"),
    NIOULAND("Niuland"),
    PHEK("Phek"),
    PIREN("Piren"),
    TUENSANG("Tuensang"),
    WOKHA("Wokha"),
    ZUNHEBOTO("Zunheboto"),
    ANGUL("Angul"),
    BALANGIR("Balangir"),
    BALESHWAR("Baleshwar"),
    BARGARH("Bargarh"),
    BHADRAK("Bhadrak"),
    BOUDH("Boudh"),
    CUTTACK("Cuttack"),
    DEOGARH("Deogarh"),
    DHENKANAL("Dhenkanal"),
    GAJAPATI("Gajapati"),
    GANJAM("Ganjam"),
    JAGATSINGHPUR("Jagatsinghpur"),
    JAJPUR("Jajpur"),
    JHARSUGUDA("Jharsuguda"),
    KALAHANDI("Kalahandi"),
    KANDHAMAL("Kandhamal"),
    KENDRAPARA("Kendrapara"),
    KENDUJHAR("Kendujhar"),
    KHORDHA("Khordha"),
    KORAPUT("Koraput"),
    MALKANGIRI("Malkangiri"),
    MAYURBHANJ("Mayurbhanj"),
    NABARANGPUR("Nabarangpur"),
    NAYAGARH("Nayagarh"),
    NUAPADA("Nuapada"),
    PURI("Puri"),
    RAYAGADA("Rayagada"),
    SAMBALPUR("Sambalpur"),
    SONEPUR("Sonepur"),
    SUNDARGARH("Sundargarh"),
    AMRITSAR("Amritsar"),
    BARNALA("Barnala"),
    BATHINDA("Bathinda"),
    FARIDKOT("Faridkot"),
    FATEHGARH_SAHIB("Fatehgarh Sahib"),
    FAZILKA("Fazilka"),
    FIROZEPUR("Firozepur"),
    GURDASPUR("Gurdaspur"),
    HOSHIARPUR("Hoshiarpur"),
    JALANDHAR("Jalandhar"),
    KAPURTHALA("Kapurthala"),
    LUDHIANA("Ludhiana"),
    MALERKOTLA("Malerkotla"),
    MANSA("Mansa"),
    MOGA("Moga"),
    MUKTSAR("Muktsar"),
    NAWANSHAHR("Nawanshahr"),
    PATHANKOT("Pathankot"),
    PATIALA("Patiala"),
    RUPNAGAR("Rupnagar"),
    SANGRUR("Sangrur"),
    SAS_NAGAR("SAS Nagar"),
    TARN_TARAN("Tarn Taran"),
    AJMER("Ajmer"),
    ALWAR("Alwar"),
    BANSWARA("Banswara"),
    BARAN("Baran"),
    BARMER("Barmer"),
    BHARATPUR("Bharatpur"),
    BHILWARA("Bhilwara"),
    BIKANER("Bikaner"),
    BUNDI("Bundi"),
    CHITTORGARH("Chittorgarh"),
    CHURU("Churu"),
    DAUSA("Dausa"),
    DHOLPUR("Dholpur"),
    DUNGARPUR("Dungarpur"),
    HANUMANGARH("Hanumangarh"),
    JAIPUR("Jaipur"),
    JAISALMER("Jaisalmer"),
    JALORE("Jalore"),
    JHALAWAR("Jhalawar"),
    JHUNJHUNU("Jhunjhunu"),
    JODHPUR("Jodhpur"),
    KARAULI("Karauli"),
    KOTA("Kota"),
    NAGAUR("Nagaur"),
    PALI("Pali"),
    PRATAPGARH("Pratapgarh"),
    RAJSAMAND("Rajsamand"),
    SAWAI_MADHOPUR("Sawai Madhopur"),
    SIKAR("Sikar"),
    SIROHI("Sirohi"),
    TONK("Tonk"),
    UDAIPUR("Udaipur"),
    CHENNAI("Chennai"),
    COIMBATORE("Coimbatore"),
    CUDDALORE("Cuddalore"),
    DHARMAPURI("Dharmapuri"),
    DINDIGUL("Dindigul"),
    ERODE("Erode"),
    KANCHIPURAM("Kanchipuram"),
    KANYAKUMARI("Kanyakumari"),
    KARUR("Karur"),
    MADURAI("Madurai"),
    NAGAPATTINAM("Nagapattinam"),
    NAMAKKAL("Namakkal"),
    NILGIRIS("Nilgiris"),
    PERAMBALUR("Perambalur"),
    PUDUKKOTTAI("Pudukkottai"),
    RAMANATHAPURAM("Ramanathapuram"),
    SALEM("Salem"),
    SIVAGANGA("Sivaganga"),
    THANJAVUR("Thanjavur"),
    THOOTHUKUDI("Thoothukudi"),
    TIRUCHIRAPPALLI("Tiruchirappalli"),
    TIRUNELVELI("Tirunelveli"),
    TIRUVANNAMALAI("Tiruvannamalai"),
    TIRUVARUR("Tiruvarur"),
    VELLORE("Vellore"),
    VILLUPURAM("Villupuram"),
    VIRUDHUNAGAR("Virudhunagar"),
    EAST_SIKKIM("East Sikkim"),
    NORTH_SIKKIM("North Sikkim"),
    SOUTH_SIKKIM("South Sikkim"),
    WEST_SIKKIM("West Sikkim"),
    ADILABAD("Adilabad"),
    BHADRADRI_KOTHAGUDEM("Bhadradri Kothagudem"),
    HANUMAKONDA("Hanumakonda"),
    HYDERABAD("Hyderabad"),
    JAGTIAL("Jagtial"),
    JANGAON("Jangaon"),
    JAYASHANKAR_BHUPALAPALLY("Jayashankar Bhupalapally"),
    JOGULAMBA_GADWAL("Jogulamba Gadwal"),
    KAMAREDDY("Kamareddy"),
    KARIMNAGAR("Karimnagar"),
    KHAMMAM("Khammam"),
    KOMARAM_BHEEM_ASIFABAD("Komaram Bheem Asifabad"),
    MAHABUBABAD("Mahabubabad"),
    MAHABUBNAGAR("Mahabubnagar"),
    MANCHERIAL("Mancherial"),
    MEDAK("Medak"),
    MEDCHAL_MALKAGIRI("Medchal-Malkajgiri"),
    MULUGU("Mulugu"),
    NAGARKURNOOL("Nagarkurnool"),
    NALGONDA("Nalgonda"),
    NARAYANPET("Narayanpet"),
    NIRMAL("Nirmal"),
    NIZAMABAD("Nizamabad"),
    PEDDAPALLI("Peddapalli"),
    RAJANNA_SIRCILLA("Rajanna Sircilla"),
    RANGAREDDY("Rangareddy"),
    SANGAREDDY("Sangareddy"),
    SIDDIPET("Siddipet"),
    SURYAPET("Suryapet"),
    VIKARABAD("Vikarabad"),
    WANAPARTHY("Wanaparthy"),
    WARANGAL("Warangal"),
    YADADRI_BHUVANAGIRI("Yadadri Bhuvanagiri"),
    DHALAI("Dhalai"),
    GOMATI("Gomati"),
    KHOWAI("Khowai"),
    NORTH_TRIPURA("North Tripura"),
    SEPAHIJALA("Sepahijala"),
    SOUTH_TRIPURA("South Tripura"),
    UNAKOTI("Unakoti"),
    WEST_TRIPURA("West Tripura"),
    AGRA("Agra"),
    ALIGARH("Aligarh"),
    ALLAHABAD("Allahabad"),
    AMBEDKAR_NAGAR("Ambedkar Nagar"),
    AMETHI("Amethi"),
    AMROHA("Amroha"),
    AURAIYA("Auraiya"),
    AZAMGARH("Azamgarh"),
    BAGHPAT("Baghpat"),
    BAHRAICH("Bahraich"),
    BALLIA("Ballia"),
    BANDA("Banda"),
    BARABANKI("Barabanki"),
    BAREILLY("Bareilly"),
    BASTI("Basti"),
    BHADOHI("Bhadohi"),
    BIJNOR("Bijnor"),
    BUDAUN("Budaun"),
    BULANDSHAHR("Bulandshahr"),
    CHANDAULI("Chandauli"),
    CHITRAKOOT("Chitrakoot"),
    DEORIA("Deoria"),
    ETAH("Etah"),
    ETAWAH("Etawah"),
    FAIZABAD("Faizabad"),
    FARRUKHABAD("Farrukhabad"),
    FATEHPUR("Fatehpur"),
    FIROZABAD("Firozabad"),
    GAUTAM_BUDDHA_NAGAR("Gautam Buddha Nagar"),
    GHAZIABAD("Ghaziabad"),
    GHAZIPUR("Ghazipur"),
    GONDA("Gonda"),
    GORAKHPUR("Gorakhpur"),
    HAMIRPUR_UP("Hamirpur"),
    HARDOI("Hardoi"),
    HATHRAS("Hathras"),
    JALAUN("Jalaun"),
    JAUNPUR("Jaunpur"),
    JHANSI("Jhansi"),
    KANNAUJ("Kannauj"),
    KANPUR_DEHAT("Kanpur Dehat"),
    KANPUR_NAGAR("Kanpur Nagar"),
    KAUSHAMBI("Kaushambi"),
    KHERI("Kheri"),
    KUSHINAGAR("Kushinagar"),
    LALITPUR("Lalitpur"),
    LUCKNOW("Lucknow"),
    MAHARAJGANJ("Maharajganj"),
    MAHOBA("Mahoba"),
    MAINPURI("Mainpuri"),
    MATHURA("Mathura"),
    MAU("Mau"),
    MEERUT("Meerut"),
    MIRZAPUR("Mirzapur"),
    MORADABAD("Moradabad"),
    MUZAFFARNAGAR("Muzaffarnagar"),
    PILIBHIT("Pilibhit"),
    RAE_BARELI("Rae Bareli"),
    RAMPUR("Rampur"),
    SAHARANPUR("Saharanpur"),
    SHAHJAHANPUR("Shahjahanpur"),
    SHRAWASTI("Shrawasti"),
    SIDDHARTHNAGAR("Siddharthnagar"),
    SITAPUR("Sitapur"),
    SONBHADRA("Sonbhadra"),
    SULTANPUR("Sultanpur"),
    UNNAO("Unnao"),
    VARANASI("Varanasi"),
    ALMORA("Almora"),
    BAGESHWAR("Bageshwar"),
    CHAMOLI("Chamoli"),
    CHAMPAWAT("Champawat"),
    DEHRADUN("Dehradun"),
    HARIDWAR("Haridwar"),
    NAINITAL("Nainital"),
    PAURI_GARHWAL("Pauri Garhwal"),
    PITHORAGARH("Pithoragarh"),
    RUDRAPRAYAG("Rudraprayag"),
    ALIPURDUAR("Alipurduar"),
    BANKURA("Bankura"),
    BIRBHUM("Birbhum"),
    COOCH_BEHAR("Cooch Behar"),
    DAKSHIN_DINAJPUR("Dakshin Dinajpur"),
    DARJEELING("Darjeeling"),
    HOOGHLY("Hooghly"),
    HOWRAH("Howrah"),
    JALPAIGURI("Jalpaiguri"),
    JAMALPUR("Jamalpur"),
    JHARGRAM("Jhargram"),
    KALIMPONG("Kalimpong"),
    KOLKATA("Kolkata"),
    MALDA("Malda"),
    MURSHIDABAD("Murshidabad"),
    NADIA("Nadia"),
    NORTH_24_PARGANAS("North 24 Parganas"),
    PASCHIM_BARDHAMAN("Paschim Bardhaman"),
    PASCHIM_MEDINIPUR("Paschim Medinipur"),
    PURBA_BARDHAMAN("Purba Bardhaman"),
    PURBA_MEDINIPUR("Purba Medinipur"),
    PURULIA("Purulia"),
    SOUTH_24_PARGANAS("South 24 Parganas"),
    UTTAR_DINAJPUR("Uttar Dinajpur"),
    NICOBAR("Nicobar"),
    NORTH_AND_MIDDLE_ANDAMAN("North and Middle Andaman"),
    SOUTH_ANDAMAN("South Andaman"),
    CHANDIGARH("Chandigarh"),
    DADRA_AND_NAGAR_HAVELI("Dadra and Nagar Haveli"),
    DAMAN("Daman"),
    DIU("Diu"),
    KARGIL("Kargil"),
    LEH("Leh"),
    AGATTI("Agatti"),
    AMINI("Amini"),
    ANDROTH("Androth"),
    BITHRA("Bithra"),
    CHETLAT("Chetlat"),
    KADMAT("Kadmat"),
    KALPENI("Kalpeni"),
    KAVARATTI("Kavaratti"),
    KILTAN("Kiltan"),
    MINICOY("Minicoy"),
    KARAIKAL("Karaikal"),
    MAHE("Mahe"),
    PUDUCHERRY("Puducherry"),
    YANAM("Yanam"),
    TEHRI_GARHWAL("Tehri Garhwal"),
    UDHAM_SINGH_NAGAR("Udham Singh Nagar"),
    UTTARKASHI("Uttarkashi");

    private final String districtName;

}
